project:
  type: website
  output-dir: _site

execute:
  cache: true

website:
  title: "Métodos Numéricos y Probabilidades 2025"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
      - text:  "Unidad 1"
        menu:
          - text: "Funcionamiento de la CPU"
            href: 01_funcionamiento_cpu.qmd
          - text: "Repaso de Python"
            href: 02_python.qmd
          - text: "Repaso de numpy, matplotlib, archivos"
            href: 03_numpy_arrays.qmd
          - text: "Representación de números y condicionamiento"
            href: 04_numeros_y_condicionamiento.qmd
          - text: "Algoritmos y estabilidad"
            href: 05_algoritmos_y_estabilidad.qmd
      - text: "Unidad 2"
        menu:
          - text: "Propiedades de la probabilidad"
            href: 06_definicion_probabilidad.qmd
          - text: "Distribuciones de probabilidad"
            href: 07_distribuciones.qmd
          - text: "Varias variables aleatorias"
            href: 08_varias_variables_aleatorias.qmd
          - text: "Teorema central del límite"
            href: 09_teorema_central_del_limite.qmd
          - text: "Entropía de Shannon"
            href: 10_entropia.qmd
      - text: "Unidad 3"
        menu:
          - text: "Solución de Sistemas de Ecuaciones Lineales"
            href: 11_solucion_sistemas_lineales.qmd
          - text: "Solución de Ecuaciones No Lineales"
            href: 12_newton_y_biseccion.qmd
          - text: "Interpolación"
            href: 13_interpolacion.qmd
          - text: "Integración Numérica"
            href: 14_integracion_numerica.qmd
          - text: "Quadratura de Gauss, integrales múltiples e impropias"
            href: 15_integrales_multiples_impropias_y_gauss.qmd
          - text: "Derivadas numéricas"
            href: 16_derivadas.qmd
      - text: "Unidad 4"
        menu:
          - text: "Métodos de Taylor"
            href: 17_metodos_de_taylor.qmd
          - text: "Métodos de Runge-Kutta"
            href: 18_runge_kutta.qmd
          - text: "Métodos de Múltiples Pasos"
            href: 19_metodos_de_multiples_pasos.qmd
          - text: "Ecuaciones de alto orden y estabilidad"
            href: 20_edo_alto_orden_estabilidad.qmd
      - text: "Unidad 5"
        menu:
          - text: "Ajustes de mínimos cuadrados"
            href: 21_ajuste_de_curvas.qmd
          - text: "Descenso de gradiente"
            href: 22_descenso_de_gradiente.qmd
          - text: "Redes neuronales"
            href: 23_redes_neuronales.qmd
  sidebar:
    style: docked
    contents:
      - section: "Unidad 1: Introducción"
        contents:
          - text: "Funcionamiento de la CPU"
            href: 01_funcionamiento_cpu.qmd
          - text: "Repaso de Python"
            href: 02_python.qmd
          - text: "Repaso de numpy, matplotlib, archivos"
            href: 03_numpy_arrays.qmd
          - text: "Representación de números y condicionamiento"
            href: 04_numeros_y_condicionamiento.qmd
          - text: "Algoritmos y estabilidad"
            href: 05_algoritmos_y_estabilidad.qmd
      - section: "Unidad 2: Probabilidad"
        contents:
          - text: "Propiedades de la probabilidad"
            href: 06_definicion_probabilidad.qmd
          - text: "Distribuciones de probabilidad"
            href: 07_distribuciones.qmd
          - text: "Varias variables aleatorias"
            href: 08_varias_variables_aleatorias.qmd
          - text: "Teorema central del límite"
            href: 09_teorema_central_del_limite.qmd
          - text: "Entropía de Shannon"
            href: 10_entropia.qmd
      - section: "Unidad 3: Cálculo Numérico"
        contents:
          - text: "Solución de Sistemas de Ecuaciones Lineales"
            href: 11_solucion_sistemas_lineales.qmd
          - text: "Solución de Ecuaciones No Lineales"
            href: 12_newton_y_biseccion.qmd
          - text: "Interpolación"
            href: 13_interpolacion.qmd
          - text: "Integración Numérica"
            href: 14_integracion_numerica.qmd
          - text: "Quadratura de Gauss, integrales múltiples e impropias"
            href: 15_integrales_multiples_impropias_y_gauss.qmd
          - text: "Derivadas numéricas"
            href: 16_derivadas.qmd
      - section: "Unidad 4: Ecuaciones Diferenciales"
        contents:
          - text: "Métodos de Taylor"
            href: 17_metodos_de_taylor.qmd
          - text: "Métodos de Runge-Kutta"
            href: 18_runge_kutta.qmd
          - text: "Métodos de Múltiples Pasos"
            href: 19_metodos_de_multiples_pasos.qmd
          - text: "Ecuaciones de alto orden y estabilidad"
            href: 20_edo_alto_orden_estabilidad.qmd
      - section: "Unidad 5: Tópicos"
        contents:
          - text: "Ajustes de mínimos cuadrados"
            href: 21_ajuste_de_curvas.qmd
          - text: "Descenso de gradiente"
            href: 22_descenso_de_gradiente.qmd
          - text: "Redes neuronales"
            href: 23_redes_neuronales.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    sidebar:
      style: floating
      collapse-level: 2



